// <auto-generated />
namespace ECommerce2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addState1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addState1));
        
        string IMigrationMetadata.Id
        {
            get { return "201711142052450_addState1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
